package com.mrh0.createaddition.index;
import com.mrh0.createaddition.CreateAddition;
import com.mrh0.createaddition.blocks.alternator.AlternatorBlock;
import com.mrh0.createaddition.blocks.barbed_wire.BarbedWireBlock;
import com.mrh0.createaddition.blocks.cake.CACakeBlock;
import com.mrh0.createaddition.blocks.connector.*;
import com.mrh0.createaddition.blocks.creative_energy.CreativeEnergyBlock;
import com.mrh0.createaddition.blocks.digital_adapter.DigitalAdapterBlock;
import com.mrh0.createaddition.blocks.digital_adapter.DigitalAdapterBlockItem;
import com.mrh0.createaddition.blocks.electric_motor.ElectricMotorBlock;
import com.mrh0.createaddition.blocks.liquid_blaze_burner.LiquidBlazeBurnerBlock;
import com.mrh0.createaddition.blocks.modular_accumulator.*;
import com.mrh0.createaddition.blocks.portable_energy_interface.PortableEnergyInterfaceBlock;
import com.mrh0.createaddition.blocks.redstone_relay.RedstoneRelayBlock;
import com.mrh0.createaddition.blocks.rolling_mill.RollingMillBlock;
import com.mrh0.createaddition.blocks.tesla_coil.TeslaCoilBlock;
import com.mrh0.createaddition.item.BiomassPelletBlock;
import com.simibubi.create.foundation.data.SharedProperties;
import com.simibubi.create.content.processing.AssemblyOperatorBlockItem;
import com.simibubi.create.foundation.data.AssetLookup;
import com.tterrag.registrate.util.entry.BlockEntry;
import static com.simibubi.create.foundation.data.ModelGen.customItemModel;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
public class CABlocks {
    public static final BlockEntry<ElectricMotorBlock> ELECTRIC_MOTOR = CreateAddition.REGISTRATE.block("electric_motor", ElectricMotorBlock::new).initialProperties(SharedProperties::softMetal).properties(BlockBehaviour.Properties::noOcclusion).item().transform(customItemModel()).register();
    public static final BlockEntry<AlternatorBlock> ALTERNATOR = CreateAddition.REGISTRATE.block("alternator", AlternatorBlock::new).initialProperties(SharedProperties::softMetal).properties(BlockBehaviour.Properties::noOcclusion).item().transform(customItemModel()).register();
    public static final BlockEntry<RollingMillBlock> ROLLING_MILL = CreateAddition.REGISTRATE.block("rolling_mill", RollingMillBlock::new).initialProperties(SharedProperties::stone).properties(BlockBehaviour.Properties::noOcclusion).item().transform(customItemModel()).register();
    public static final BlockEntry<CreativeEnergyBlock> CREATIVE_ENERGY = CreateAddition.REGISTRATE.block("creative_energy", CreativeEnergyBlock::new).initialProperties(SharedProperties::softMetal).properties(BlockBehaviour.Properties::noOcclusion).item().properties(p -> p.rarity(Rarity.EPIC)).transform(customItemModel()).register();
    public static final BlockEntry<SmallConnectorBlock> SMALL_CONNECTOR = CreateAddition.REGISTRATE.block("connector", SmallConnectorBlock::new).initialProperties(SharedProperties::stone).properties(BlockBehaviour.Properties::noOcclusion).item().transform(customItemModel()).register();
    public static final BlockEntry<SmallLightConnectorBlock> SMALL_LIGHT_CONNECTOR = CreateAddition.REGISTRATE.block("small_light_connector", SmallLightConnectorBlock::new).initialProperties(SharedProperties::stone).properties(BlockBehaviour.Properties::noOcclusion).item().transform(customItemModel()).register();
    public static final BlockEntry<LargeConnectorBlock> LARGE_CONNECTOR = CreateAddition.REGISTRATE.block("large_connector", LargeConnectorBlock::new).initialProperties(SharedProperties::stone).properties(BlockBehaviour.Properties::noOcclusion).item().transform(customItemModel()).register();
    public static final BlockEntry<RedstoneRelayBlock> REDSTONE_RELAY = CreateAddition.REGISTRATE.block("redstone_relay", RedstoneRelayBlock::new).initialProperties(SharedProperties::stone).properties(BlockBehaviour.Properties::noOcclusion).item().transform(customItemModel()).register();
    public static final BlockEntry<CACakeBlock> CHOCOLATE_CAKE = CreateAddition.REGISTRATE.block("chocolate_cake", CACakeBlock::new).initialProperties(() -> Blocks.CAKE).properties(props -> props.sound(SoundType.WOOL).strength(0.5f).noOcclusion()).item().transform(customItemModel()).register();
    public static final BlockEntry<CACakeBlock> HONEY_CAKE = CreateAddition.REGISTRATE.block("honey_cake", CACakeBlock::new).initialProperties(() -> Blocks.CAKE).properties(props -> props.sound(SoundType.WOOL).strength(0.5f).noOcclusion()).item().transform(customItemModel()).register();
    public static final BlockEntry<BarbedWireBlock> BARBED_WIRE = CreateAddition.REGISTRATE.block("barbed_wire", BarbedWireBlock::new).initialProperties(() -> Blocks.COBWEB).properties(props -> props.noCollission().noOcclusion().requiresCorrectToolForDrops().strength(4.0F)).item().transform(customItemModel()).register();
    public static final BlockEntry<TeslaCoilBlock> TESLA_COIL = CreateAddition.REGISTRATE.block("tesla_coil", TeslaCoilBlock::new).initialProperties(SharedProperties::softMetal).properties(BlockBehaviour.Properties::noOcclusion).item(AssemblyOperatorBlockItem::new).transform(customItemModel()).register();
    public static final BlockEntry<ModularAccumulatorBlock> MODULAR_ACCUMULATOR = CreateAddition.REGISTRATE.block("modular_accumulator", ModularAccumulatorBlock::regular).initialProperties(SharedProperties::softMetal).properties(BlockBehaviour.Properties::noOcclusion).addLayer(() -> RenderType::cutoutMipped).item(ModularAccumulatorBlockItem::new).transform(customItemModel()).register();
    public static final BlockEntry<LiquidBlazeBurnerBlock> LIQUID_BLAZE_BURNER = CreateAddition.REGISTRATE.block("liquid_blaze_burner", LiquidBlazeBurnerBlock::new).initialProperties(SharedProperties::softMetal).properties(p -> p.mapColor(DyeColor.GRAY).noOcclusion()).addLayer(() -> RenderType::cutoutMipped).register();
    public static final BlockEntry<PortableEnergyInterfaceBlock> PORTABLE_ENERGY_INTERFACE = CreateAddition.REGISTRATE.block("portable_energy_interface", PortableEnergyInterfaceBlock::new).initialProperties(SharedProperties::softMetal).properties(BlockBehaviour.Properties::noOcclusion).addLayer(() -> RenderType::cutoutMipped).item().transform(customItemModel()).register();
    public static final BlockEntry<Block> BIOMASS_PALLET = CreateAddition.REGISTRATE.block("biomass_pellet_block", Block::new).initialProperties(() -> Blocks.DRIED_KELP_BLOCK).properties(p -> p.mapColor(MapColor.COLOR_GREEN)).item(BiomassPelletBlock::new).transform(customItemModel()).register();
    public static final BlockEntry<Block> ELECTRUM_BLOCK = CreateAddition.REGISTRATE.block("electrum_block", Block::new).initialProperties(() -> Blocks.GOLD_BLOCK).properties(p -> p.mapColor(MapColor.TERRACOTTA_YELLOW)).item().transform(customItemModel()).register();
    public static final BlockEntry<DigitalAdapterBlock> DIGITAL_ADAPTER = CreateAddition.REGISTRATE.block("digital_adapter", DigitalAdapterBlock::new).initialProperties(SharedProperties::softMetal).properties(p -> p.mapColor(DyeColor.GRAY)).item(DigitalAdapterBlockItem::new).transform(customItemModel()).register();
    public static void register() {}
}
